apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarr-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/media/sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sonarr-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarr-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/plex/Television
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sonarr-storage
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-downloads-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarr-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/plex/Downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sonarr-storage
  resources:
    requests:
      storage: 500Gi
