apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - externalsecret.yaml
  - custom-resources.yaml
  - bgp-peer.yaml
  - management-cluster-connection.yaml