apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mission-control-secret
  namespace: mission-control
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-secret-store
  target:
    name: mission-control-secret
  data:
    - secretKey: postgres_user
      remoteRef:
        key: MC_POSTGRES_USER
    - secretKey: postgres_password
      remoteRef:
        key: MC_POSTGRES_PASSWORD
    - secretKey: clerk_secret_key
      remoteRef:
        key: MC_CLERK_SECRET_KEY
    - secretKey: clerk_publishable_key
      remoteRef:
        key: MC_CLERK_PUBLISHABLE_KEY
    - secretKey: local_auth_token
      remoteRef:
        key: MC_LOCAL_AUTH_TOKEN
