---
apiVersion: rbac.authorization.k8s.io/v1
project: default
kind: ClusterRoleBinding
metadata:
  name: headlamp
subjects:
- kind: User
  name: "drew.payment@gmail.com" # Please note that the name is case-sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin