apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-secrets
  namespace: headlamp
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-secret-store
  target:
    name: headlamp-secrets
  data:
    - secretKey: oidc_client_id
      remoteRef:
        key: HEADLAMP_CONFIG_OIDC_CLIENT_ID
    - secretKey: oidc_client_secret
      remoteRef:
        key: HEADLAMP_CONFIG_OIDC_CLIENT_SECRET