apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - externalsecret.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - create-token-job.yaml
  - http-route.yaml
  