# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: headlamp
#   namespace: headlamp
#   labels:
#     app.kubernetes.io/name: headlamp
# secrets:
#   - name: headlamp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp
subjects:
- kind: User
  name: "drew.payment@gmail.com" # Please note that the name is case-sensitive
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  namespace: kube-system
  name: headlamp-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin