apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.86.44
  share: /mnt/tank/appdata
  subDir: kubernetes-pvcs
reclaimPolicy: Retain
volumeBindingMode: Immediate
