
storageClass:
  create: true
  name: tank-db
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  provisioner: nfs.csi.k8s.io
  parameters:
    server: 192.168.86.44
    share: /mnt/tank/db
  reclaimPolicy: Retain
  volumeBindingNode: Immediate