defaultPodOptions:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: *app
controllers:
  libreddit:
    type: statefulset
    annotations:
      reloader.stakater.com/auto: 'true'
    containers:
      app:
        image:
          repository: quay.io/redlib/redlib
          tag: latest
          pullPolicy: Always
        env:
          REDLIB_DEFAULT_SHOW_NSFW: on
          REDLIB_DEFAULT_WIDE: on
          REDLIB_DEFAULT_USE_HLS: on
          REDLIB_DEFAULT_HIDE_HLS_NOTIFICATION: on

        resources:
          requests:
            cpu: 5m
            memory: 50Mi
          limits:
            memory: 850Mi
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /settings
                port: &port 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false

service:
  app:
    controller: libreddit
    ports:
      http:
        port: *port
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "reddit.hoytlabs.app"
    hosts:
      - host: &host 'reddit.hoytlabs.app'
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host

fullNameOverride: *app
podAnnotations:
  reloader.stakater.com/auto: 'true'
  setGateway: 'true'