originRequest:
  originServerName: "external.hoytlabs.app"

ingress:
  - hostname: "hoytlabs.app"
    service: https://cilium-gateway-gateway-external.gateway.svc.cluster.local:443
  - hostname: "*.hoytlabs.app"
    service: https://cilium-gateway-gateway-external.gateway.svc.cluster.local:443
  - service: http_status:404