apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tigera-operator
rules:
  # Core API resources
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - podtemplates
      - services
      - endpoints
      - events
      - configmaps
      - secrets
      - serviceaccounts
      - nodes
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - resourcequotas
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - calico-critical-pods
      - tigera-critical-pods
    resources:
      - resourcequotas
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  # RBAC
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - rolebindings
      - roles
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
      - bind
      - escalate
  # Apps
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - delete
      - watch
  - apiGroups:
      - apps
    resourceNames:
      - tigera-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  # Batch - REQUIRED FOR v1.32.3
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  # Storage - REQUIRED FOR v1.32.3
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  # Networking
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
  # Policy
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
      - use
  # Scheduling
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  # Monitoring
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - prometheusrules
      - alertmanagers
      - podmonitors
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  # Tigera operator CRDs
  - apiGroups:
      - operator.tigera.io
    resources:
      - "*"
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
      - patch
  # Calico CRDs - REQUIRED FOR v1.32.3
  - apiGroups:
      - projectcalico.org
      - crd.projectcalico.org
    resources:
      - "*"
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
      - patch
  # Elasticsearch/Kibana (for enterprise features)
  - apiGroups:
      - elasticsearch.k8s.elastic.co
    resources:
      - elasticsearches
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kibana.k8s.elastic.co
    resources:
      - kibanas
    verbs:
      - get
      - list
      - watch
  # API extensions
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  # API registration
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  # Admissionregistration
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  # Coordination
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  # Discovery
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
