---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: affine-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drewpayment/hoytlabs-talos.git
    targetRevision: HEAD
    path: apps/affine/app
  destination:
    server: https://kubernetes.default.svc
    namespace: apps