apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: affine-db-secret
  namespace: affine
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-secret-store
  target:
    name: affine-db-secret
  data:
    - secretKey: affine_pg_user
      remoteRef:
        key: AFFINE_PG_USER
    - secretKey: affine_pg_password
      remoteRef:
        key: AFFINE_PG_PASSWORD