apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kestra

resources: 
  - namespace.yaml
  - http-route.yaml
  - networkpolicy.yaml
  - storageclass.yaml
  
helmCharts:
  - name: kestra
    repo: https://helm.kestra.io/
    version: 0.22.0
    releaseName: kestra
    namespace: kestra
    valuesFile: values.yaml
    includeCRDs: true