apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kestra

resources: 
  - namespace.yaml
  
helmCharts:
  - name: kestra
    repo: https://helm.kestra.io/
    version: 0.22.9
    releaseName: kestra
    namespace: kestra
    valuesFile: values.yaml