# Only customize what we need, let the official Helm chart handle defaults

# Disable ingress since we're using HTTPRoute for external access
ingress:
  enabled: true
# Disable Docker-in-Docker (not compatible with Talos security policies)
dind:
  enabled: false
  
minio: 
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
  persistence: 
    existingClaim: kestra-pvc
    storageClass: kestra-storage
    
postgresql:
  primary: 
    podSecurityContext:
      enabled: true
      fsGroup: 999
    containerSecurityContext:
      enabled: true
      runAsUser: 999
      runAsGroup: 999
      runAsNonRoot: true
    persistence: 
      existingClaim: kestra-pvc
      storageClass: kestra-storage
  
# Resource configuration - increased memory for standalone mode
# Use Kubernetes task runner instead of Docker-in-Docker for script execution
pluginDefaults:
  - type: io.kestra.plugin.scripts
    forced: true
    values:
      taskRunner:
        type: io.kestra.plugin.kubernetes.runner.Kubernetes
        namespace: kestra
# Resource configuration for better performance
resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 3Gi
    cpu: 2000m