apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harness-secrets
  namespace: harness
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-secret-store
  target:
    name: harness-secrets
  data:
    - secretKey: admin_password
      remoteRef:
        key: GITNESS_PRINCIPAL_ADMIN_PASSWORD
