apiVersion: v1
kind: PersistentVolume
metadata:
  name: harness-data-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harness-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/harness/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harness-data
  namespace: harness
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: harness-storage
  resources:
    requests:
      storage: 100Gi
