apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-hoytlabs
  namespace: gateway
spec:
  dnsNames:
    - "*.hoytlabs.app"
    - hoytlabs.app
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-hoytlabs-th8s6
  usages:
    - digital signature
    - key encipherment