apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # Gateway resources
  - namespace.yaml
  - gateway-class.yaml
  - gw-external.yaml
  - gw-internal.yaml
  - externalsecret.yaml
  - cert-hoytlabs.yaml


generatorOptions:
  disableNameSuffixHash: true