apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-externalsecret
  namespace: networking
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: doppler-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret
    creationPolicy: Owner
    # The template section defines the structure of the Kubernetes Secret.
    # The keys here (TUNNEL_ID, credentials.json) are the keys that will be in the K8s Secret.
    # The values (e.g., {{ .CLOUDFLARED_TUNNEL_ID_KEY }}) are Go template expressions
    # that will be populated by the data fetched by the 'data' block below.
    template:
      data:
        TUNNEL_ID: "{{ .CLOUDFLARED_TUNNEL_ID_KEY }}" # Maps to 'secretKey' from 'data' block
        credentials.json: "{{ .CLOUDFLARED_CREDENTIALS_JSON_KEY }}" # Maps to 'secretKey' from 'data' block
  # The 'data' block specifies which secrets to fetch from the external provider (Doppler)
  # and what to name their values in the templating context (via 'secretKey').
  data:
    - secretKey: CLOUDFLARED_TUNNEL_ID_KEY # This is the key used in the template above
      remoteRef:
        key: CLOUDFLARED_TUNNEL_ID # Actual name/path of the secret in Doppler
        # property: (optional) if CLOUDFLARED_TUNNEL_ID is a JSON object in Doppler and you need a specific field
    - secretKey: CLOUDFLARED_CREDENTIALS_JSON_KEY # This is the key used in the template above
      remoteRef:
        key: CLOUDFLARED_CREDENTIALS_JSON # Actual name/path of the secret in Doppler
        # property: (optional)