apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-externalsecret
  namespace: networking
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: doppler-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret
  # The 'data' block specifies which secrets to fetch from the external provider (Doppler)
  # and what to name their values in the templating context (via 'secretKey').
  data:
    - secretKey: CLOUDFLARED_TUNNEL_ID
      remoteRef:
        key: CLOUDFLARED_TUNNEL_ID
        # property: (optional) if CLOUDFLARED_TUNNEL_ID is a JSON object in Doppler and you need a specific field
    - secretKey: CLOUDFLARED_CREDENTIALS_JSON
      remoteRef:
        key: CLOUDFLARED_CREDENTIALS_JSON