apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-externalsecret
  namespace: networking
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: doppler-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret
    creationPolicy: Owner
    template:
      engine: golang
      data:
        TUNNEL_ID: "{{ .CLOUDFLARED_TUNNEL_ID }}"
        credentials.json: "{{ .CLOUDFLARED_CREDENTIALS_JSON }}"
  data:
    - secretKey: CLOUDFLARED_TUNNEL_ID
    - secretKey: CLOUDFLARED_CREDENTIALS_JSON