apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

namespace: cloudflared

resources:
  - namespace.yaml
  - externalsecret.yaml
  - daemon-set.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: config
    files:
      - config.yaml
  