apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal

resources: 
  - namespace.yaml
  
helmCharts:
  - name: temporal
    repo: https://go.temporal.io/helm-charts/
    version: 0.63.0
    releaseName: temporal 
    namespace: temporal
    valuesFile: values.yaml
    