apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-cluster-secret-store
spec:
  provider:
    doppler:
      authToken:
        secretRef:
          name: doppler-token
          namespace: external-secrets
          key: token
