# externalsecret-tunnel-id-configmap.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-id-provider
  namespace: networking
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: doppler-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-tunnel-data
    kind: ConfigMap
    creationPolicy: Owner
    template:
      data:
        TUNNEL_ID: "{{ .CLOUDFLARED_TUNNEL_ID }}"
  data:
    - secretKey: CLOUDFLARED_TUNNEL_ID