apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-external-secrets
  namespace: hoarder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-secret-store
  target:
    name: hoarder-secrets
  data:
    - secretKey: meili_master_key
      remoteRef: 
        key: MEILI_MASTER_KEY
    - secretKey: next_public_secret
      remoteRef:
        key: NEXT_PUBLIC_SECRET
    - secretKey: next_auth_secret
      remoteRef: 
        key: NEXTAUTH_SECRET
    - secretKey: openai_base_url
      remoteRef: 
        key: OPENAI_BASE_URL
    - secretKey: openai_api_key
      remoteRef: 
        key: OPENAI_API_KEY
    - secretKey: inference_text_model
      remoteRef: 
        key: INFERENCE_TEXT_MODEL
    - secretKey: inference_image_model
      remoteRef: 
        key: INFERENCE_IMAGE_MODEL
    - secretKey: embedding_text_model
      remoteRef: 
        key: EMBEDDING_TEXT_MODEL
    - secretKey: inference_text_length
      remoteRef: 
        key: INFERENCE_CONTEXT_LENGTH
    - secretKey: disable_signups
      remoteRef: 
        key: DISABLE_SIGNUPS