apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-config
  namespace: atlas
data:
  BETTER_AUTH_URL: "https://atlas.hoytlabs.app"
  TRUSTED_ORIGINS: "https://atlas.hoytlabs.app"
  NODE_ENV: "production"
