---
# MongoDB PV + PVC
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orbit-mongodb-pv
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orbit-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/orbit/mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: orbit-storage
  resources:
    requests:
      storage: 20Gi
  volumeName: orbit-mongodb-pv

---
# PostgreSQL PV + PVC
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orbit-postgresql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orbit-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/orbit/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: orbit-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: orbit-postgresql-pv

---
# Redis PV + PVC
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orbit-redis-pv
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orbit-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/orbit/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: orbit-storage
  resources:
    requests:
      storage: 5Gi
  volumeName: orbit-redis-pv

---
# Redpanda PV + PVC
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orbit-redpanda-pv
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orbit-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/orbit/redpanda
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: orbit-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: orbit-redpanda-pv

---
# MinIO PV + PVC
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orbit-minio-pv
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orbit-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/orbit/minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: orbit-storage
  resources:
    requests:
      storage: 20Gi
  volumeName: orbit-minio-pv

---
# BuildKit PV + PVC
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orbit-buildkit-pv
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orbit-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/orbit/buildkit
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-cache
spec:
  accessModes: [ReadWriteMany]
  storageClassName: orbit-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: orbit-buildkit-pv
