apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: redpanda
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      serviceAccountName: orbit
      securityContext:
        runAsUser: 0
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v24.2.10
          args:
            - redpanda
            - start
            - --kafka-addr
            - internal://0.0.0.0:9092
            - --advertise-kafka-addr
            - internal://redpanda:9092
            - --rpc-addr
            - redpanda:33145
            - --advertise-rpc-addr
            - redpanda:33145
            - --mode
            - dev-container
            - --smp
            - "1"
            - --default-log-level=warn
          ports:
            - name: kafka
              containerPort: 9092
            - name: admin
              containerPort: 9644
          volumeMounts:
            - name: data
              mountPath: /var/lib/redpanda/data
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 500m
          readinessProbe:
            exec:
              command: ["rpk", "cluster", "health", "--exit-when-healthy"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["rpk", "cluster", "health", "--exit-when-healthy"]
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 10Gi
