config:
  hoytlabs-talos:nodeIps:
    - "192.168.86.200"
    - "192.168.86.204" 
    - "192.168.86.201"  
  hoytlabs-talos:vip: "192.168.86.220"
  hoytlabs-talos:talosctlPath: "talosctl"
  hoytlabs-talos:talosOutputDir: "./talos"