config:
  hoytlabs-talos:nodeIps:
    - "192.168.86.200"
    - "192.168.86.204" 
    - "192.168.86.201"  
  hoytlabs-talos:vip: "192.168.86.220"
  hoytlabs-talos:talosctlPath: "talosctl"
  hoytlabs-talos:talosOutputDir: "./talos"
  nodeConfig:
    - ip: 192.168.86.200
      hostname: kube-master-msi-1
      filename: controlplane-msi.yaml
      deviceSelector:
        busPath: 0*
    - ip: 192.168.86.204
      hostname: kube-master-dell-1
      filename: controlplane-dell.yaml
      deviceSelector:
        busPath: 0*
    - ip: 192.168.86.201
      hostname: kube-master-opti-1
      filename: controlplane-opti.yaml
      deviceSelector:
        busPath: 0*
  kubernetes: 1.33.0
  machine:
    install:
      image: factory.talos.dev/nocloud-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0