apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - cidr: "192.168.86.208/28"  # Usable IPs: 192.168.86.209 to 192.168.86.222
  allowFirstLastIPs: "No"