apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-cluster-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            namespace: external-secrets
            key: token
