apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-secret
  namespace: infisical
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-secret-store
  target:
    name: infisical-secret
  data:
    # openssl rand -hex 16
    - secretKey: encryption_key
      remoteRef:
        key: INFISICAL_ENCRYPTION_KEY
    # openssl rand -base64 32
    - secretKey: auth_secret
      remoteRef:
        key: INFISICAL_AUTH_SECRET
    - secretKey: postgres_user
      remoteRef:
        key: INFISICAL_POSTGRES_USER
    - secretKey: postgres_password
      remoteRef:
        key: INFISICAL_POSTGRES_PASSWORD
    # Resend SMTP credentials (username is literally "resend").
    - secretKey: smtp_username
      remoteRef:
        key: INFISICAL_SMTP_USERNAME
    - secretKey: smtp_password
      remoteRef:
        key: INFISICAL_SMTP_PASSWORD
