apiVersion: apps/v1
kind: Deployment
metadata:
  name: infisical-redis
  namespace: infisical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infisical-redis
  template:
    metadata:
      labels:
        app: infisical-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
